Updated security-iac-scan.yml

diff --git a/security-pipeline-tasks/security-iac-scan.yml b/security-pipeline-tasks/security-iac-scan.yml
--- a/security-pipeline-tasks/security-iac-scan.yml
+++ b/security-pipeline-tasks/security-iac-scan.yml
@@ -10,11 +10,13 @@ steps:
 - script: |
     mkdir $(Agent.TempDirectory)/tfsec -m 777
     cmd="docker run --rm -v "${{ parameters.sourceDirectory }}:/src" -v "$(Agent.TempDirectory)/tfsec:/report"  aquasec/tfsec:latest --format="sarif" --out="/report/tfsec-scan.sarif" /src "
-    if [ "${{ parameters.failBuildOnFindings}}" ]
-    then
-      cmd+="|| true "
-    fi
     eval $cmd
+    exitCode=$?
+    fail="${{ parameters.failBuildOnFindings}}"
+    if ! [ $fail ]; then
+      exit 0
+    fi
+    exit $exitCode
   displayName: Run TF-Sec
   condition: succeededOrFailed()
 
